version: 0.2

phases:
  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
      - "unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init
      - echo `terraform workspace new ${ENVIRONMENT_NAME}`
      - terraform workspace list
      - terraform workspace select ${ENVIRONMENT_NAME}
  build:
    commands:
      - terraform plan -var-file=./environments/env.${ENVIRONMENT_NAME}.tfvars
      - terraform apply -var-file=./environments/env.${ENVIRONMENT_NAME}.tfvars -auto-approve
  post_build:
    commands:
      - echo terraform apply completed on `date`
