version: 0.2

phases:     
  build:
    commands:
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"
  post_build:
    commands:
      - echo Post Build Started successfully on `date`